In [1]:
import numpy as np

In [31]:
def gram_schmidt(A):
    # Criar matriz Q
    Q = np.zeros(A.shape)
    # Atualizando 1ª coluna com a 1ª coluna de A normalizada    
    for i in range(A.shape[1]):
        # Vetor i de Q recebe o vetor i de A
        Q[:, i] = A[:, i]
        # Somatório das projeções de a em Q
        for j in range(i):
            # formula para compor o q chapéu
            Q[:, i] -= Q[:, j].T @ A[:, i] * Q[:, j]
        # Normalização do vetor q, com arredondamento
        Q[:, i] /= abs(np.linalg.norm(Q[:, i])) \
        < 1e-8 and 1 or np.linalg.norm(Q[:, i])
        #Q[:, i] /= np.linalg.norm(Q[:, i])
        
    return Q

In [30]:
A = np.array([[1, 1, 2, 0, 1, 1],
              [0, 0, 0, 1, 2, 1],
              [1, 2, 3, 1, 3, 2],
              [1, 0, 1, 0, 1, 1]])

Q = gram_schmidt(A)
Q.round(5)

array([[ 0.57735, -0.     , -0.     , -0.30861, -0.     , -0.     ],
       [ 0.     ,  0.     ,  0.     ,  0.92582,  0.     ,  0.     ],
       [ 0.57735,  0.70711,  0.     ,  0.1543 ,  0.     ,  0.     ],
       [ 0.57735, -0.70711, -0.     ,  0.1543 , -0.     , -0.     ]])

In [32]:
(Q.T @ Q).round(5) 

array([[ 1., -0., -0., -0., -0., -0.],
       [-0.,  1.,  0.,  0.,  0.,  0.],
       [-0.,  0.,  0.,  0.,  0.,  0.],
       [-0.,  0.,  0.,  1.,  0.,  0.],
       [-0.,  0.,  0.,  0.,  0.,  0.],
       [-0.,  0.,  0.,  0.,  0.,  0.]])

In [33]:
A = np.array([
    [1, 1, -1],
    [1, 2, 1],
    [1, 3, 0]
], dtype=float)

Q = gram_schmidt(A)
Q.round(5)

array([[ 0.57735, -0.70711, -0.40825],
       [ 0.57735, -0.     ,  0.8165 ],
       [ 0.57735,  0.70711, -0.40825]])

In [34]:
(Q.T @ Q).round(5) 

array([[ 1., -0.,  0.],
       [-0.,  1.,  0.],
       [ 0.,  0.,  1.]])