In [2]:
import numpy as np
import itertools as it
from scipy.linalg import lu
import matplotlib.pyplot as plt

In [3]:
def gram_schmidt(A):
    # Criar matriz Q
    Q = np.zeros(A.shape)
    # Atualização dos vetores/colunas de    
    for i in range(A.shape[1]):
        # Vetor i de Q recebe o vetor i de A
        Q[:, i] = A[:, i]
        # Somatório das projeções dos vetores de A em Q
        for j in range(i):
            # formula para compor o q chapéu
            Q[:, i] -= Q[:, j].T @ A[:, i] * Q[:, j]
        # Normalização do vetor q
        #Q[:, i] /= np.linalg.norm(Q[:, i])
        # arredondamento, se divisao for muito pequena, aproximamos a 1, para reduzir erro numérico
        Q[:, i] /= np.linalg.norm(Q[:, i]) < 1e-8 and 1 or np.linalg.norm(Q[:, i])
        
    R = Q.T @ A
    return Q,R

In [11]:
#Gera uma matriz LI
#obs: Manter os prints :) 
def matrizLI(m,n):
    A=np.random.randint(0,5,(m,n))        #Gera uma mxn aleatória
    p,l,u = lu(A)                         #Faz a decomposicao LU dela
    #print('A antes=',A)
    #print('u=',u)
    delj,deli = [],[]
    
    sup_indices = np.triu_indices(n)      #Retorna 1 lista com os 'i's e outra lista com os 'j's da parte superior
    
    for i,j in zip(sup_indices[0],sup_indices[1]):
        if i!=j and u[i][j]==0:       #Percorre a parte superior da matriz U e checa aonde existe 0 
            #print('deleta coluna',j)
            deli.append(i)           #Lista as linhas onde existe o 0
            delj.append(j)           #Lista as colunas onde existe 0 pra deleta-las
               
    for i,j in it.product(deli,delj):
        A=np.delete(A,j,axis=1)           #Deleta as colunas listadas.
        e0 = np.eye(m)[i]
        #print('e0=',e0)
        A=np.insert(A, j, e0, axis=1)     #Coloca o vetor ei(coluna i da identidade) no lugar do vetor que deixava LD
    
    #print('A depois=',A)
    #p,l,u = lu(A)
    #print('u depois=',u)
    return A



In [13]:
# Corrigir erros de arredondamento.

# Matriz LI
A = matrizLI(7,5)
print('A=',A,'\n')
#A = np.array([
#    [1, 1, -1],
#    [1, 2, 1],
#    [1, 3, 0]
#], dtype=float)

# Matriz Q
Q,R = gram_schmidt(A)
# Arredondando a 5 casas decimais
print('Q=',Q.round(5))

A= [[1 1 1 4 1]
 [0 2 0 3 0]
 [2 1 0 1 0]
 [1 1 0 1 0]
 [4 2 0 2 0]
 [2 1 0 2 0]
 [3 1 0 2 0]] 

Q= [[ 0.16903  0.23615  0.9569  -0.      -0.     ]
 [ 0.       0.91835 -0.22663  0.20438  0.     ]
 [ 0.33806  0.01312 -0.06295 -0.24526 -0.     ]
 [ 0.16903  0.23615 -0.08814 -0.26569 -0.     ]
 [ 0.67612  0.02624 -0.12591 -0.49051 -0.     ]
 [ 0.33806  0.01312 -0.06295  0.53139  0.     ]
 [ 0.50709 -0.20991 -0.03777  0.55183  0.     ]]


In [14]:
# Q ortogonal
(Q.T @ Q).round(5)

array([[ 1.,  0., -0.,  0.,  0.],
       [ 0.,  1., -0., -0., -0.],
       [-0., -0.,  1., -0., -0.],
       [ 0., -0., -0.,  1.,  0.],
       [ 0., -0., -0.,  0.,  0.]])

In [15]:
# Teoricamente normalizada
np.linalg.norm(Q).round(5)

2.0

In [16]:
# Matriz R
R.round(5)

array([[ 5.91608,  2.87352,  0.16903,  4.22577,  0.16903],
       [ 0.     ,  2.17781,  0.23615,  3.60782,  0.23615],
       [ 0.     , -0.     ,  0.9569 ,  2.54335,  0.9569 ],
       [ 0.     , -0.     , -0.     ,  1.28759, -0.     ],
       [ 0.     , -0.     , -0.     ,  0.     , -0.     ]])

In [17]:
# Decomposição Completa
(Q @ R).round(5)

array([[ 1.,  1.,  1.,  4.,  1.],
       [ 0.,  2., -0.,  3., -0.],
       [ 2.,  1.,  0.,  1.,  0.],
       [ 1.,  1.,  0.,  1.,  0.],
       [ 4.,  2.,  0.,  2.,  0.],
       [ 2.,  1., -0.,  2., -0.],
       [ 3.,  1., -0.,  2., -0.]])