In [5]:
import numpy as np
import itertools as it
from scipy.linalg import lu
import matplotlib.pyplot as plt

In [11]:
def gram_schmidt(A):
    # Criar matriz Q
    Q = np.zeros(A.shape)
    # Atualização dos vetores/colunas de    
    for i in range(A.shape[1]):
        # Vetor i de Q recebe o vetor i de A
        Q[:, i] = A[:, i]
        # Somatório das projeções dos vetores de A em Q
        for j in range(i):
            # formula para compor o q chapéu
            Q[:, i] -= Q[:, j].T @ A[:, i] * Q[:, j]
        # Normalização do vetor q
        #Q[:, i] /= np.linalg.norm(Q[:, i])
        # arredondamento, se divisao for muito pequena, aproximamos a 1, para reduzir erro numérico
        Q[:, i] /= np.linalg.norm(Q[:, i]) < 1e-8 and 1 or np.linalg.norm(Q[:, i])
        
    R = Q.T @ A
    return Q,R

In [25]:
#Gera uma matriz LI
#obs: Manter os prints :) 

def matrizLI(m,n):
    A=np.random.randint(0,5,(m,n))        #Gera uma mxn aleatória
    p,l,u = lu(A)                         #Faz a decomposicao LU dela
    #print('A antes=',A)
    #print('u=',u)
    delj,deli = [],[]
    
    for i in range(m):
        for j in range(n):
            if i<=j and u[i][j]==0:      #Percorre toda matriz U e checa aonde existe 0 na parte superior
                #print('deleta coluna',j)
                deli.append(i)           #Lista as linhas onde existe o 0
                delj.append(j)           #Lista as colunas onde existe 0 pra deleta-las 
               
    for i,j in it.product(deli,delj):
        e0 = [0]*m
        A=np.delete(A,j,axis=1)           #Deleta as colunas listadas.
        e0[i] = 1
        #print('e0=',e0)
        A=np.insert(A, j, e0, axis=1)     #Coloca o vetor ei(coluna i da identidade) no lugar do vetor que deixava LD
    
    #print('A depois=',A)
    #p,l,u = lu(A)
    #print('u depois=',u)
    return A

In [27]:
# Corrigir erros de arredondamento.

# Matriz LI
A = matrizLI(7,5)
print('A=',A,'\n')
#A = np.array([
#    [1, 1, -1],
#    [1, 2, 1],
#    [1, 3, 0]
#], dtype=float)

# Matriz Q
Q,R = gram_schmidt(A)
# Arredondando a 5 casas decimais
print('Q=',Q.round(5))

A= [[0 1 2 1 1]
 [3 0 0 4 0]
 [1 0 2 3 0]
 [4 0 2 1 0]
 [2 0 4 2 0]
 [1 0 0 4 0]
 [0 0 1 2 0]] 

Q= [[ 0.       1.       0.       0.       0.     ]
 [ 0.53882  0.      -0.45669  0.32586  0.     ]
 [ 0.17961  0.       0.37212  0.37229  0.     ]
 [ 0.71842  0.      -0.08457 -0.47599  0.     ]
 [ 0.35921  0.       0.74424 -0.03818  0.     ]
 [ 0.17961  0.      -0.15223  0.63046  0.     ]
 [ 0.       0.       0.26218  0.36014  0.     ]]


In [28]:
# Q ortogonal
(Q.T @ Q).round(5)

array([[ 1.,  0.,  0., -0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [-0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [269]:
# Teoricamente normalizada
np.linalg.norm(Q).round(5)

2.23607

In [29]:
# Matriz R
R.round(5)

array([[ 5.56776,  0.     ,  3.2329 ,  4.84934,  0.     ],
       [ 0.     ,  1.     ,  2.     ,  1.     ,  1.     ],
       [-0.     ,  0.     ,  3.81423,  0.60892,  0.     ],
       [-0.     ,  0.     , -0.     ,  5.1101 ,  0.     ],
       [ 0.     ,  0.     ,  0.     ,  0.     ,  0.     ]])

In [30]:
# Decomposição Completa
(Q @ R).round(5)

array([[ 0.,  1.,  2.,  1.,  1.],
       [ 3.,  0.,  0.,  4.,  0.],
       [ 1.,  0.,  2.,  3.,  0.],
       [ 4.,  0.,  2.,  1.,  0.],
       [ 2.,  0.,  4.,  2.,  0.],
       [ 1.,  0., -0.,  4.,  0.],
       [-0.,  0.,  1.,  2.,  0.]])