In [240]:
import numpy as np
from scipy.linalg import lu
import matplotlib.pyplot as plt

In [253]:
def gram_schmidt(A):
    # Criar matriz Q
    Q = np.zeros(A.shape)
    # Atualização dos vetores/colunas de    
    for i in range(A.shape[1]):
        # Vetor i de Q recebe o vetor i de A
        Q[:, i] = A[:, i]
        # Somatório das projeções dos vetores de A em Q
        for j in range(i):
            # formula para compor o q chapéu
            Q[:, i] -= Q[:, j].T @ A[:, i] * Q[:, j]
        # Normalização do vetor q
        #Q[:, i] /= np.linalg.norm(Q[:, i])
        # arredondamento, se divisao for muito pequena, aproximamos a 1, para reduzir erro numérico
        Q[:, i] /= np.linalg.norm(Q[:, i]) < 1e-8 and 1 or np.linalg.norm(Q[:, i])
        
    R = Q.T @ A
    return Q,R

In [254]:
#Gera uma matriz LI
#obs: Manter os prints :) 

def matrizLI(m,n):
    A=np.random.randint(0,5,(m,n))        #Gera uma mxn aleatória
    p,l,u = lu(A)                         #Faz a decomposicao LU dela
    #print('A antes=',A)
    #print('u=',u)
    dels = []
    
    for i in range(m):
        for j in range(n):
            if i<=j and u[i][j]==0:      #Percorre toda matriz U e checa aonde existe 0 na parte superior
                #print('deleta coluna',j)
                dels.append(j)           #Lista as colunas onde existe 0 pra deleta-las 
               
    A=np.delete(A,dels,axis=1)           #Deleta as colunas listadas.
    
    #print('A depois=',A)
    #p,l,u = lu(A)
    #print('u depois=',u)
    return A

In [267]:
# Corrigir erros de arredondamento.

# Matriz LI
A = matrizLI(7,5)
print('A=',A,'\n')
#A = np.array([
#    [1, 1, -1],
#    [1, 2, 1],
#    [1, 3, 0]
#], dtype=float)

# Matriz Q
Q,R = gram_schmidt(A)
# Arredondando a 5 casas decimais
print('Q=',Q.round(5))

A= [[3 3 2 4 4]
 [1 4 1 0 2]
 [3 2 4 0 4]
 [3 2 4 3 3]
 [3 1 0 0 0]
 [2 1 1 0 2]
 [2 2 1 4 1]] 

Q= [[ 0.44721  0.201   -0.14112  0.40771  0.63703]
 [ 0.14907  0.88927 -0.11926 -0.35286 -0.18427]
 [ 0.44721 -0.07309  0.51132 -0.42575  0.11742]
 [ 0.44721 -0.07309  0.51132  0.22865 -0.40711]
 [ 0.44721 -0.34718 -0.62214 -0.31021 -0.33189]
 [ 0.29814 -0.14009 -0.13615 -0.24107  0.40067]
 [ 0.29814  0.134   -0.1933   0.5669  -0.3317 ]]


In [268]:
# Q ortogonal
(Q.T @ Q).round(5)

array([[ 1.,  0.,  0.,  0., -0.],
       [ 0.,  1., -0.,  0.,  0.],
       [ 0., -0.,  1., -0., -0.],
       [ 0.,  0., -0.,  1., -0.],
       [-0.,  0., -0., -0.,  1.]])

In [269]:
# Teoricamente normalizada
np.linalg.norm(Q).round(5)

2.23607

In [270]:
# Matriz R
R.round(5)

array([[ 6.7082 ,  5.06842,  5.21749,  4.32306,  6.11192],
       [ 0.     ,  3.64844,  0.70045,  1.12072,  1.92472],
       [ 0.     ,  0.     ,  3.35963,  0.19628,  2.31065],
       [ 0.     ,  0.     ,  0.     ,  4.58438, -0.00716],
       [-0.     , -0.     , -0.     , -0.     ,  1.89756]])

In [271]:
# Decomposição Completa
(Q @ R).round(5)

array([[ 3.,  3.,  2.,  4.,  4.],
       [ 1.,  4.,  1.,  0.,  2.],
       [ 3.,  2.,  4., -0.,  4.],
       [ 3.,  2.,  4.,  3.,  3.],
       [ 3.,  1.,  0.,  0.,  0.],
       [ 2.,  1.,  1., -0.,  2.],
       [ 2.,  2.,  1.,  4.,  1.]])