In [36]:
import numpy as np
import math

In [88]:
def rotation(a,b):
    norma = math.hypot(a,b)
    cos = a/norma
    sen = -b/norma
    return (cos,sen)

In [137]:
def givens_rotation(A):
    qtd_linhas, qtd_colunas = A.shape
    Q = np.identity(A.shape[0])
    R = np.copy(A)
    linhas, colunas = np.tril_indices(qtd_linhas, -1, qtd_colunas)
    i = 0
    for (linha, coluna) in zip(linhas, colunas):
        if(R[linha,coluna] != 0):
            cos, sen = rotation(R[coluna, coluna], R[linha,coluna])
            G = np.identity(qtd_linhas)
            G[[coluna,linha],[coluna,linha]] = cos
            G[linha, coluna] = sen
            G[coluna, linha] = -sen
            R = np.dot(G, R)
            Q = np.dot(Q,G.T)
        i = i+1
        print("Matriz Q{}:\n{}".format(i, Q.round(5)))
    return (Q,R)

In [138]:
A = np.array([[12,-51,4],
            [6,167,-68],
            [-4,24,-41]])

Q, R = givens_rotation(A)
separador = 40*'-'
print("{}\nMatriz Q:\n{}\nMatriz R:\n{}\n".format(separador,Q.round(5), R.round(5)))

Matriz Q1:
[[ 0.89443 -0.44721  0.     ]
 [ 0.44721  0.89443  0.     ]
 [ 0.       0.       1.     ]]
Matriz Q2:
[[ 0.85714 -0.44721  0.25555]
 [ 0.42857  0.89443  0.12778]
 [-0.28571  0.       0.95831]]
Matriz Q3:
[[ 0.85714 -0.39429  0.33143]
 [ 0.42857  0.90286 -0.03429]
 [-0.28571  0.17143  0.94286]]
----------------------------------------
Matriz Q:
[[ 0.85714 -0.39429  0.33143]
 [ 0.42857  0.90286 -0.03429]
 [-0.28571  0.17143  0.94286]]
Matriz R:
[[ 14.  21. -14.]
 [  0. 175. -70.]
 [  0.  -0. -35.]]



In [139]:
print("Matriz QR:\n{}\n\nMatriz A:\n{}\n".format(Q@R, A))

Matriz QR:
[[ 12. -51.   4.]
 [  6. 167. -68.]
 [ -4.  24. -41.]]

Matriz A:
[[ 12 -51   4]
 [  6 167 -68]
 [ -4  24 -41]]



In [140]:
a = np.linalg.inv(Q)
a

array([[ 0.85714286,  0.42857143, -0.28571429],
       [-0.39428571,  0.90285714,  0.17142857],
       [ 0.33142857, -0.03428571,  0.94285714]])

In [141]:
(Q.T@Q).round(4)

array([[ 1.,  0.,  0.],
       [ 0.,  1., -0.],
       [ 0., -0.,  1.]])

In [143]:
A = np.array([[1, 1, 2, 0, 1, 1],
              [0, 0, 0, 1, 2, 1],
              [1, 2, 3, 1, 3, 2],
              [1, 0, 1, 0, 1, 1]])

Q,R = givens_rotation(A)
print("{}\nMatriz Q:\n{}\nMatriz R:\n{}\n".format(separador,Q.round(4),R.round(4)))

Matriz Q1:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Matriz Q2:
[[ 0.70711  0.      -0.70711  0.     ]
 [ 0.       1.       0.       0.     ]
 [ 0.70711  0.       0.70711  0.     ]
 [ 0.       0.       0.       1.     ]]
Matriz Q3:
[[ 0.70711 -0.70711  0.       0.     ]
 [ 0.       0.      -1.       0.     ]
 [ 0.70711  0.70711  0.       0.     ]
 [ 0.       0.       0.       1.     ]]
Matriz Q4:
[[ 0.57735 -0.70711  0.      -0.40825]
 [ 0.       0.      -1.       0.     ]
 [ 0.57735  0.70711  0.      -0.40825]
 [ 0.57735  0.       0.       0.8165 ]]
Matriz Q5:
[[ 0.57735  0.       0.      -0.8165 ]
 [ 0.       0.      -1.       0.     ]
 [ 0.57735  0.70711  0.       0.40825]
 [ 0.57735 -0.70711  0.       0.40825]]
Matriz Q6:
[[ 0.57735  0.       0.8165   0.     ]
 [ 0.       0.       0.      -1.     ]
 [ 0.57735  0.70711 -0.40825  0.     ]
 [ 0.57735 -0.70711 -0.40825  0.     ]]
----------------------------------------
Matriz Q:
[[ 0.5774  0.      0.8165  0.    ]
 [