In [36]:
import numpy as np
import math

In [88]:
def rotation(a,b):
    norma = math.hypot(a,b)
    cos = a/norma
    sen = -b/norma
    return (cos,sen)

In [114]:
def givens_rotation(A):
    qtd_linhas, qtd_colunas = A.shape
    Q = np.identity(A.shape[0])
    R = np.copy(A)
    linhas, colunas = np.tril_indices(qtd_linhas, -1, qtd_colunas)
    i = 0
    for (linha, coluna) in zip(linhas, colunas):
        if(R[linha,coluna] != 0):
            cos, sen = rotation(R[coluna, coluna], R[linha,coluna])
            G = np.identity(qtd_linhas)
            G[[coluna,linha],[coluna,linha]] = cos
            G[linha, coluna] = sen
            G[coluna, linha] = -sen
            R = np.dot(G, R)
            Q = np.dot(Q,G.T)
        i = i+1
        print("Matriz Q{}:\n{}".format(i, Q))
    return (Q,R)

In [120]:
A = np.array([[12,-51,4],
            [6,167,-68],
            [-4,24,-41]])

Q, R = givens_rotation(A)
print("Matriz Q:\n{}\n".format(Q))
print("Matriz R:\n{}\n".format(R))

Matriz Q1:
[[ 0.89442719 -0.4472136   0.        ]
 [ 0.4472136   0.89442719  0.        ]
 [ 0.          0.          1.        ]]
Matriz Q2:
[[ 0.85714286 -0.4472136   0.25555063]
 [ 0.42857143  0.89442719  0.12777531]
 [-0.28571429  0.          0.95831485]]
Matriz Q3:
[[ 0.85714286 -0.39428571  0.33142857]
 [ 0.42857143  0.90285714 -0.03428571]
 [-0.28571429  0.17142857  0.94285714]]
Matriz Q:
[[ 0.85714286 -0.39428571  0.33142857]
 [ 0.42857143  0.90285714 -0.03428571]
 [-0.28571429  0.17142857  0.94285714]]

Matriz R:
[[ 1.40000000e+01  2.10000000e+01 -1.40000000e+01]
 [ 7.94410929e-17  1.75000000e+02 -7.00000000e+01]
 [ 4.36926011e-16 -3.78902318e-16 -3.50000000e+01]]



array([[ 12., -51.,   4.],
       [  6., 167., -68.],
       [ -4.,  24., -41.]])

In [121]:
a = np.linalg.inv(Q)
a

array([[ 0.85714286,  0.42857143, -0.28571429],
       [-0.39428571,  0.90285714,  0.17142857],
       [ 0.33142857, -0.03428571,  0.94285714]])

In [92]:
(Q.T@Q).round(4)

array([[ 1.,  0.,  0.],
       [ 0.,  1., -0.],
       [ 0., -0.,  1.]])